title: Zubair Abid
logo: /assets/img/profile.jpg
description: Software Engineer at Microsoft. CSE @ IIIT-Hyderabad.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
permalink: /:title.html
